### ISSUE TITLE
Todo List:

### ISSUE THREAD

**Issue by Paralaxus** [Andrew2070/Empires-Mod#9]
**Major:**
- [ ] Add HeroChat/Deluxechat support.
- [ ] Create Empire Chat Channel: /empire chat
- [ ] Create Empire Ally chat channel: /empire chat ally
- [ ] Add auto-download option for detected mods lacking protection files.
- [ ] Add forcible/configurable taxes on Empire citizens to be paid/real day.
- [ ] Finish wiki, add permissions nodes and command help.
- [ ] Add Dynmap support. (Show empire borders as shaded regions).
- [ ] Update to 1.8
- [ ] Update to 1.1
- [ ] Create NPC AI powered guards.

**Notice**
 Updates to future MC iterations will require me to do the following:
-> Fix Relationships.
-> Add Relationships to sql db.
-> Fix the non-dangerous directory issue with ReflectASM.

**Minor:**
- [ ] Add some more configuration options.
- [ ] Add some more administrator commands.
- [ ] Turn Chat Prefix [Empire] into an Empire object rather than a string (for hover info)
- [ ] Possibly add sponge support
